---
- hosts: all
  become: yes
  tasks:
  - name: i am going to ping all my nodes
    ping:
  - name: install webserver
    apt:
     name: apache2
  - name: yes i am install tree
    apt:
     name: tree
     state: present
